#!/bin/sh

rm -rf ~/topcat_tmp
cp -r /vagrant ~/topcat_tmp
cd ~/topcat_tmp
mvn -q clean install
cp ~/topcat_tmp/target/topcat-*.zip ~/
cd ~/
unzip -o topcat-*.zip
cd topcat
cp ~/topcat_tmp/provision/topcat.properties /home/vagrant/topcat/topcat.properties
cp ~/topcat_tmp/provision/topcat-setup.properties /home/vagrant/topcat/topcat-setup.properties
cp ~/topcat_tmp/yo/app/config/topcat_dev.json /home/vagrant/topcat/topcat.json
cp ~/topcat_tmp/yo/app/languages/lang.json /home/vagrant/topcat/lang.json
cp ~/topcat_tmp/yo/app/styles/topcat.css /home/vagrant/topcat/topcat.css
dos2unix ./setup
chmod 0755 ./setup
./setup configure
./setup install

