function bit(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',hb='&',r='/',nc='1046A68999A2C75682D38DFA263F5F80.cache.html',fc='17E60430D93B31BCA4E8A26B01F59368.cache.html',pc='2463001E99B8B5E479829D85375EBD0A.cache.html',cc='4051A8163C3AFC0DD3365AA32250ED6E.cache.html',hc='4753BF05300710931D06B4621E187D9A.cache.html',Db='495D43C7D040E7BB052B716130C42C20.cache.html',ic='4E4C77C105655236B1DE2891998915C2.cache.html',Fb='663AE8618F95935C018EEE090135700B.cache.html',mc='78C0C43BF6F7CBC3CE9C113DC82EE85B.cache.html',qc='85D6B115DD52AE987CADE87259772A1E.cache.html',gc='988FCE310D37F1E4419666F9B4E79830.cache.html',yc='<script defer="defer">bit.onInjectionDone(\'bit\')<\/script>',Ac='<script id="',A='=',q='?',Cb='A02CB1D5B82CE4AFACFC4D83392ECBF7.cache.html',bc='A31B3808213E4CCF1A83820CFBE70B85.cache.html',jc='BA7A081303C778B1C3C0810E2FC8467D.cache.html',C='Bad handler "',ac='CB1451863A9207B002E671BD2A73D13C.cache.html',kc='D93E4DA2F138B13704D4FFE08AA1C081.cache.html',ec='DBE4460E99DBF87F1BFFE7AAF839D14A.cache.html',xc='DOMContentLoaded',lc='EAB5FF5F96260E63E72B31D14DA7BD23.cache.html',o='SCRIPT',lb='Unexpected exception in locale detection, using default: ',kb='_',ib='__gwt_Locale',zc='__gwt_marker_bit',s='base',nb='begin',m='bit',cb='bootstrap',u='clear.cache.gif',z='content',jb='default',Eb='en',Bb='en_DI',oc='end',ub='gecko',vb='gecko1_8',yb='gwt.hybrid',rc='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',wc='head',zb='hosted.html?bit',vc='href',tb='ie6',sb='ie8',ab='iframe',t='img',bb="javascript:''",sc='link',xb='loadExternalRefs',fb='locale',gb='locale=',v='meta',eb='moduleRequested',dc='moduleStartup',rb='msie',w='name',ob='opera',db='position:absolute;width:0;height:0;border:none',tc='rel',qb='safari',Ab='selectingPermutation',x='startup',uc='stylesheet',wb='unknown',mb='user.agent',pb='webkit';var Cc=window,k=document,Bc=Cc.__gwtStatsEvent?function(a){return Cc.__gwtStatsEvent(a)}:null,qd,gd,bd,ad=l,jd={},td=[],pd=[],Fc=[],md,od;Bc&&Bc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!Cc.__gwt_stylesLoaded){Cc.__gwt_stylesLoaded={}}if(!Cc.__gwt_scriptsLoaded){Cc.__gwt_scriptsLoaded={}}function fd(){var b=false;try{b=Cc.external&&(Cc.external.gwtOnLoad&&Cc.location.search.indexOf(yb)==-1)}catch(a){}fd=function(){return b};return b}
function id(){if(qd&&gd){var c=k.getElementById(m);var b=c.contentWindow;if(fd()){b.__gwt_getProperty=function(a){return cd(a)}}bit=null;b.gwtOnLoad(md,m,ad);Bc&&Bc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:oc})}}
function dd(){var j,h=zc,i;k.write(Ac+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){ad=f(j.src)}if(ad==l){var e=k.getElementsByTagName(s);if(e.length>0){ad=e[e.length-1].href}else{ad=f(k.location.href)}}else if(ad.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=ad+u;ad=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function nd(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}jd[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{od=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{md=eval(b)}catch(a){alert(C+b+F)}}}}}}
function Ec(a,b){return b in td[a]}
function Dc(a){var b=jd[a];return b==null?null:b}
function sd(d,e){var a=Fc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function cd(d){var e=pd[d](),b=td[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(od){od(d,a,e)}throw null}
var ed;function hd(){if(!ed){ed=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);Bc&&Bc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(ad+rd)}}
pd[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(gb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(hb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=Dc(fb)}if(g==null){g=Cc[ib]}if(g==null){return jb}while(!Ec(fb,g)){var f=g.lastIndexOf(kb);if(f==-1){g=jb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(lb+a);return jb}};td[fb]={'default':0,en:1,en_DI:2};pd[mb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(ob)!=-1){return ob}else if(d.indexOf(pb)!=-1){return qb}else if(d.indexOf(rb)!=-1){if(document.documentMode>=8){return sb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return tb}}}}else if(d.indexOf(ub)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return vb}return ub}return wb};td[mb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};bit.onScriptLoad=function(){if(ed){gd=true;id()}};bit.onInjectionDone=function(){qd=true;Bc&&Bc({moduleName:m,subSystem:x,evtGroup:xb,millis:(new Date()).getTime(),type:oc});id()};dd();var rd;if(fd()){if(Cc.external.initModule&&Cc.external.initModule(m)){Cc.location.reload();return}rd=zb}nd();Bc&&Bc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:Ab});if(!rd){try{sd([Bb,ob],Cb);sd([jb,ob],Db);sd([Eb,ob],Fb);sd([Bb,vb],ac);sd([jb,vb],bc);sd([Eb,vb],cc);sd([Bb,qb],ec);sd([jb,qb],fc);sd([Eb,qb],gc);sd([Bb,ub],hc);sd([jb,ub],ic);sd([Eb,ub],jc);sd([Bb,tb],kc);sd([jb,tb],lc);sd([Eb,tb],mc);sd([Bb,sb],nc);sd([jb,sb],pc);sd([Eb,sb],qc);rd=Fc[cd(fb)][cd(mb)]}catch(a){return}}var ld;function kd(){if(!bd){bd=true;if(!__gwt_stylesLoaded[rc]){var a=k.createElement(sc);__gwt_stylesLoaded[rc]=a;a.setAttribute(tc,uc);a.setAttribute(vc,ad+rc);k.getElementsByTagName(wc)[0].appendChild(a)}id();if(k.removeEventListener){k.removeEventListener(xc,kd,false)}if(ld){clearInterval(ld)}}}
if(k.addEventListener){k.addEventListener(xc,function(){hd();kd()},false)}var ld=setInterval(function(){if(/loaded|complete/.test(k.readyState)){hd();kd()}},50);Bc&&Bc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:oc});Bc&&Bc({moduleName:m,subSystem:x,evtGroup:xb,millis:(new Date()).getTime(),type:nb});k.write(yc)}
bit();