
CREATE TABLE `CONFVAR` (
  `NAME` varchar(255) NOT NULL,
  `VALUE` text,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `DOWNLOAD` ADD `THE_SIZE` bigint(20) DEFAULT NULL;
