#!/usr/bin/env python
from setup_utils import *
import os

# TopCAT

def uninstall():
    app = actions.getAppName("TopCAT")
    if app: actions.asadmin("undeploy " + app)

    app = actions.getAppName("TopCATAdmin")
    if app: actions.asadmin("undeploy " + app)

    actions.asadmin("delete-jdbc-resource jdbc/TopCATDB", tolerant=True)
    actions.asadmin("delete-jdbc-connection-pool TopCATDB", tolerant=True)   
    
    actions.deleteFileRealmUser(props["adminUsername"]);
    

actions, options, arg = getActions()
props = actions.getGlassfish("topcat-setup.properties", ["dbProperties", "glassfish", "driver", "port", "topcatUrlRoot", "topcatAdminUrlRoot", "adminUsername", "adminPassword"])

prop_name = "topcat.properties"
prop_list = ["KEYWORDS_CACHED", "LOGO_URL", "ACCESSIBILITY", "PRIVACY_POLICY", "DATA_POLICY", "TERMS_OF_USE", "COMPLAINTS_PROCEDURE", "FEEDBACK"]

if arg in ["CONFIGURE", "INSTALL"]:
    actions.configure(prop_name, prop_list)
    topcatProperties = actions.getProperties(prop_name, prop_list)
    actions.checkNoErrors()
    
if arg == "INSTALL":
    actions.installFile(prop_name)
    
    try:
        uninstall()
        
        actions.addFileRealmUser(props["adminUsername"], props["adminPassword"], "topcatAdmin");
            
        actions.asadmin('create-jdbc-connection-pool --datasourceclassname ' + props["driver"] + 
                ' --restype javax.sql.DataSource --failconnection=true --steadypoolsize 2' + 
                ' --maxpoolsize 32 --ping --property ' + props["dbProperties"] + ' TopCATDB', printOutput=True)
        
        actions.asadmin("create-jdbc-resource --connectionpoolid TopCATDB jdbc/TopCATDB")
      
        actions.deploy("TopCAT-*.war", contextroot=props["topcatUrlRoot"], deploymentorder=140)
        actions.deploy("TopCATAdmin-*.war", contextroot=props["topcatAdminUrlRoot"], deploymentorder=141)
          
    except Exception, e:
        abort(str(e))

if arg == "UNINSTALL":             
    
    actions.removeFile(prop_name)
    
    try: 
        uninstall()

    except Exception, e:
        abort(str(e))       



