#!/usr/bin/env python
from setup_utils import *
import os

# topcat

def uninstall():
    app = actions.getAppName("topcat")
    if app: actions.undeploy(app)

    actions.unregisterDB("topcat")
    actions.deleteMailResource("mail/topcat")

actions, arg, props = getActions("topcat-setup.properties", ["db.vendor", "db.driver", "db.url", "db.username", "db.password"])

prop_name = "topcat.properties"
prop_list = []

if arg in ["CONFIGURE", "INSTALL"]: 
    actions.configure(prop_name, prop_list) 
    for f in ["topcat.json", "lang.json", "topcat.css"]:
        actions.configureFileForWar(f)
    actions.checkNoErrors()

if arg == "INSTALL":
    actions.installFile(prop_name)
           
    try:
        uninstall()
        actions.registerDB("topcat", props["db.vendor"], props["db.driver"], props["db.url"], props["db.username"], props["db.password"])

        if props["mail.enable"].lower() == 'true':
            actions.createMailResource("mail/topcat", props["mail.host"], props["mail.user"], props["mail.from"], props["mail.property"])
 
        files = []
        files.append(["topcat.json", "config"])
        files.append(["lang.json", "languages"])
        files.append(["topcat.css", "styles"])
        actions.deploy(files=files, deploymentorder=140)

    except Exception, e:
        abort(str(e))

else:  # UNINSTALL
    actions.removeFile(prop_name)

    try:
        uninstall();

    except Exception, e:
        abort(str(e))
